### ISSUE TITLE
Error: Option '--tag' requires an argument.

### ISSUE THREAD

**Issue by jeremy-bepoix** [python-semantic-release/upload-to-gh-release#9]
Hi, 
Since latest release i upgrade to `V9.7.3` and got this error : 

![image](https://github.com/python-semantic-release/upload-to-gh-release/assets/145460090/b5fdc51a-42b8-4cd0-87ab-4f3d59b09743)

note: 
- same on **main** branch too
- same on **v9.0.2**

To notice step build :
```
  release:
    name: Package release
    needs:
      - test
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish package to GitHub Release
      uses: python-semantic-release/upload-to-gh-release@v9.0.2
      if: ${{ steps.release.outputs.released }} == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.release.outputs.tag }}
 ```
